name: flutter_button
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.0.7
  flutter_webview_plugin: ^0.3.0+2
  flutter_swiper : ^1.1.4
  flutter_easyrefresh: ^1.2.4
  flutter_screenutil: ^0.5.1
  shared_preferences: ^0.5.1+1
  fluttertoast: ^3.0.0
  amap_base: ^0.2.12
  url_launcher: ^5.0.1
  loadmore: ^1.0.2
  pull_to_refresh: ^1.1.6
  fluro: ^1.4.0
  sqflite: ^1.1.1
  http: 0.12.0
  json_annotation: ^2.0.0
  scoped_model: 1.0.1
  path_provider: ^0.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
       - images/btn_search_clicked.png
       - images/Image_my_history_click.png
       - images/wallpapers/wallpaper1.jpg
       - images/wallpapers/wallpaper2.jpg
       - images/wallpapers/wallpaper3.jpg
       - images/bg_loading.jpg
       - images/douyu/Img_orange.png
       - images/douyu/home_header_hot.png
       - images/douyu/home_header_normal.png
       - images/douyu/home_header_phone.png
       - images/douyu/home_live_cate_normal.png
       - images/douyu/home_more_btn.png
       - images/empty_cart.png
       - images/trash-gray.png
       - images/Image_scan_click.png
       - images/Image_scan.png
       - images/hubei_tv.png
       - images/ic_start_bg.png
       - images/cctv_4.png
       - images/cctv_5.png
       - images/black_bg.9.png
       - images/ic_bookmark.png
       - images/cctv_7.png
       - images/ic_show.png
       - images/seekbar_bg.9.png
       - images/dark_dot.png
       - images/cctv_6.png
       - images/favorite_selected.png
       - images/volume_normal.png
       - images/ic_loading_hor.9.png
       - images/cctv_2.png
       - images/favorite_normal.png
       - images/cctv_3.png
       - images/cctv_1.png
       - images/ic_start.png
       - images/ic_battery_100.png
       - images/ic_light.png
       - images/fullplayer_icon_next.png
       - images/cctv_15.png
       - images/ic_comic.png
       - images/player_icon_slider.png
       - images/cctv_14.png
       - images/ic_history.png
       - images/dongfang_tv.png
       - images/cctv_13.png
       - images/iconfont_blog.png
       - images/player_pause_all_normal.png
       - images/ic_battery_10.png
       - images/cctv_12.png
       - images/cctv_10.png
       - images/beijing_tv.png
       - images/cctv_11.png
       - images/hunan_tv.png
       - images/volume_no.png
       - images/ic_documentary.png
       - images/ic_variety.png
       - images/play_checkbox.png
       - images/player_icon_slider_pressed.png
       - images/ic_action_delete.png
       - images/ic_loading.9.png
       - images/ic_music.png
       - images/ic_battery_20.png
       - images/ic_live.png
       - images/tianjing_tv.png
       - images/ic_launcher.png
       - images/iconfont_about.png
       - images/iconfont_home.png
       - images/player_play_normal.png
       - images/seekbar_progress.9.png
       - images/guide3.png
       - images/b.jpg
       - images/play_checkbox_selected.png
       - images/c.jpg
       - images/guide2.png
       - images/a.jpg
       - images/ic_battery_80.png
       - images/guide1.png
       - images/d.jpg
       - images/titlebar_return_white.png
       - images/white_dot.png
       - images/ic_movie.png
       - images/e.jpg
       - images/cctv_8.png
       - images/ic_battery_50.png
       - images/fullplayer_icon_next_disable.png
       - images/player_pause_normal.png
       - images/cctv_9.png
       - images/huobao.png
       - images/location.png
       - images/youhuiquan.png
       - images/kefudianhua.png
       - images/guanyu.png
       - images/dizhi.png
       - images/backchevronvcopy.png
       - images/backgrey.png
       - images/line.png
       - images/member/order.png
       - images/member/daifukuan.png
       - images/member/daifahuo.png
       - images/member/daishouhuo.png
       - images/member/daipingjia.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
